spring.application.name=dscommerce
spring.profiles.active=prod
spring.jpa.open-in-view=false



security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}

security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:5174,https://ds-commerce.vercel.app,https://ds-commerce-git-master-andrefelipedasilva0599-3007s-projects.vercel.app/,https://ds-commerce-hfd7fs3tj-andrefelipedasilva0599-3007s-projects.vercel.app/}

